[project]
name = "movies-scraper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "curl-cffi>=0.10.0",
    "fake-useragent>=2.2.0",
    "free-proxy>=1.1.3",
    "requests>=2.32.3",
]
